#
# Use this configuration file to control what RobotPy packages are installed
# on your RoboRIO
#

[tool.robotpy]

# Version of robotpy this project depends on
robotpy_version = "2025.2.1.0"

# Which extra RobotPy components should be installed
robotpy_extras = [
    "commands2",
    "phoenix6",
    "rev"
]

requires = [
#    "robotpy-pathplannerlib==2025.1.1",
    "robotpy-urcl==2025.0.0"
]